name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      env:
        PNPM_CACHE_DIR: ~/.pnpm-store

    - name: Lint code
      run: pnpm lint
      env:
        PNPM_CACHE_DIR: ~/.pnpm-store

    - name: Run tests
      run: pnpm test
      env:
        PNPM_CACHE_DIR: ~/.pnpm-store

    - name: Build application
      run: pnpm build
      env:
        PNPM_CACHE_DIR: ~/.pnpm-store

    - name: Run integration tests
      run: pnpm test:api
      env:
        PNPM_CACHE_DIR: ~/.pnpm-store
